name: Update Burndown Chart

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3:00 UTC
  workflow_dispatch:      # allows manual trigger

env:
  GITHUB_TOKEN: ${{ secrets.CRYPTCRAWLER_TOKEN }} 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v4
        with: 
            ref: master
            token: ${{ secrets.CRYPTCRAWLER_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install matplotlib requests

      - name: Run burndown chart generator
        run: python scripts/generate_burndown.py

      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
            ref: deploy
            path: deploy
            token: ${{ secrets.CRYPTCRAWLER_TOKEN }}

      # Move files from output/ to deploy/docs/
      - name: Move generated files into deploy/docs
        run: |
          mkdir -p deploy/docs
          cp -r output/* deploy/docs/
          ls deploy/docs/

      # Commit and push
      - name: Commit and push to deploy
        working-directory: deploy
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/burndown_log.json docs/burndown.png
          git commit -m "chore: update burndown chart" || echo "No changes to commit"
          git push origin deploy